# Dockerfile

# Use the official Python base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the app.py file into the container
COPY ../app/app.py .

# Run the application
CMD ["python", "app.py"]
